# Generated by Django 2.1.5 on 2019-02-01 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PZT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SN', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Sweep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Freq', models.TextField(help_text='List of frequency sample points, as a string')),
                ('ReZ', models.TextField(help_text='Real component')),
                ('ImZ', models.TextField(help_text='Imaginary component')),
                ('band_type', models.CharField(blank=True, choices=[('L', 'Low Freq'), ('H', 'High Freq')], default='L', max_length=1)),
                ('pzt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plotter.PZT')),
            ],
        ),
    ]
