# Generated by Django 2.1.5 on 2019-02-01 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sweep',
            name='pzt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sweep_list', to='plotter.PZT'),
        ),
    ]
