# Generated by Django 2.1.5 on 2019-02-02 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0002_auto_20190131_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='sweep',
            name='eln',
            field=models.IntegerField(default=0, help_text='Element position'),
        ),
    ]
