# Generated by Django 2.1.5 on 2019-02-02 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0003_sweep_eln'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pzt',
            name='SN',
            field=models.CharField(max_length=6),
        ),
    ]
