# Generated by Django 2.1.5 on 2019-02-02 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0004_auto_20190201_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sweep',
            name='pzt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plotter.PZT'),
        ),
    ]
